on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --mirror git@github.com:joxda/libXISF.git repo-mirror
          cd repo-mirror
          git remote add upstream https://gitea.nouspiro.space/nou/libXISF/ || true
          git fetch upstream --prune
          git push --mirror origin
