on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Fetch updates
        run: |
          git remote add upstream https://gitea.nouspiro.space/nou/libXISF/ || true
          git fetch upstream --prune
      - name: Push
        run: |
          git push origin --mirror
